//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jsonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int SampleId { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int StatusId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
